language: node_js
node_js:
  - "4.0"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
  - npm install -g firebase-admin@~4.1.2
  - npm install -g firebase-functions
after_success:
  - firebase deploy --token $FIREBASE_TOKEN